# Generated by Django 5.2 on 2025-04-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='subscription_period',
            field=models.CharField(blank=True, choices=[('MONTH', 'Месяц'), ('SEMESTER', 'Семестр'), ('YEAR', 'Год')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('RENT', 'Аренда'), ('UTILITIES', 'Коммунальные услуги'), ('SUBSCRIPTION', 'Подписка'), ('OTHER', 'Прочее')]),
        ),
    ]
