# Generated by Django 5.2 on 2025-04-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_subscription_period_alter_bill_bill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='rent_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='rent_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('RENT', 'Аренда'), ('UTILITIES', 'Коммунальные услуги'), ('SUBSCRIPTION', 'Подписка'), ('OTHER', 'Прочее')], max_length=50),
        ),
    ]
