version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  hotel-network:
    driver: bridge 