version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Для доступа к хосту из контейнера
    networks:
      - app_network

networks:
  app_network:
    driver: bridge