# Generated by Django 5.2 on 2025-04-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='available_seats',
        ),
        migrations.AddField(
            model_name='room',
            name='occupied_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='Занятые места'),
        ),
    ]
