# Generated by Django 5.2 on 2025-04-08 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_available_seats_room_occupied_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип мебели')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture', to='rooms.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Мебель',
                'verbose_name_plural': 'Мебель',
            },
        ),
    ]
