# Generated by Django 5.2 on 2025-04-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_furniture_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.CharField(default=100, max_length=10, unique=True, verbose_name='Номер комнаты'),
            preserve_default=False,
        ),
    ]
