# Generated by Django 5.2 on 2025-04-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
