# Generated by Django 5.2 on 2025-04-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
